######################################
### Configure programming language ###
######################################
language: java

##################################
### Make sure using Oracle JDK ###
##################################
jdk:
  - oraclejdk11

###################################
### Disable Email notifications ###
###################################
notifications:
  email: false

###############
### Caching ###
###############
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

#################
### SonarQube ###
#################
addons:
  sonarcloud:
    organization: "mysteryworlds"
    token:
      secure: jWdjCCgJ4LqZ9t+at/bWFuQS5pYu9kVmv3t+j0U6/NLDXOjqIUg1Z48bYF55evPNGj6wPZwHG1gC8Rbo9CBo4QGV2tfpsx3F2X16Ew6UlhPJmOx++NTAhTMK9AxsvGulP4qIWy9GNjYNeeqovtZxweivC/GGkF/Vv1FeJ6WUKAu8MJ96T/x2Cl1ai5F3Jr2mCRytH1ZRl6w2jNqJQxKVDBCG+uaTkaT+BEG4YFXuJt35bMiIQezwVeG5LbDhhYH+Ga1FTuDoItXnvOLqoBFRoefHS/SxpDhfbu6FI8E5NAVEtPjfWwvfBE2xrzva5hSrGpnTmY3X5Yyw3DUGFaFSdfLdIJG8Lfl+IzZYpHvYguGVwyN1xGInA+4BGsHzWNF70IRKuqe6QaBkXbr+ahPPpC4LxaX7GbiYVqSr16SoappkBsZhkjH30XEHuqYCNO+bOeAI3Mzv2bUDQINB7F2blZjnl23AeG9o3wUQD3ie/zrYHysZCf7AWccAdvzfo+KsQeWECKXZOIMbbLJ42KLoVzi9ov7TOn0tSHJQFFngpHXxrTmMNCeU04HXhtIk9yVB17QQFHrl1jHxr38vzCeeocK2/Ro+3vuA1T8S6YovblMWDafgTpZvBxqNr/qB0IATj6Ry8V4/X1YQ5sUB3lL7xbayshWZddRaAgVPpUu4X80=

###########################
### Actual Build Script ###
###########################
script:
  - ./gradlew build
  - ./gradlew --scan -s
  - ./gradlew codeCoverageReport
  - ./gradlew sonarqube

##################
### Deployment ###
##################
deploy:
  provider: script
  script: ./gradlew publish
  on:
    branch: master
    tags: true

###################
### Environment ###
###################
env:
  global:
    # Nexus
    - secure: H3nlRKPvLU408r40kOApKHahXR9v6zXFWmBPMzqzsYPtlRlr9yMyFsuZlI/7w+OCAEHBTCV5UDdmkEEYtpsykycBQF3ICXiEuDRHRTrskCHgK0Pm0kTk9VJqxYHts6BKdymiDpON6w/GoUWJNDxtUl38hOlyDf8fIJFdV2FFil/AkEzyz8iIGXGTkZmlSY9L6H8luBLTBhAUJcuwuByifke7vCyFERJcsyJ/4/YzmaAuAFKljPy1SHkfW/iSl3+jEgqsNvsfbZyPj/xKAEXUiElw3SwR+d7iB71UZ4TnVJxdDZkgZYVccKjihPpgNtSi86CKKAkVZCcOCTHH8vxpuKwSPnBpPT0o5ScDmwwfxXj0N9esn7dXun9dOwAIb6O4BbLxMcY/q9BXZ/E69zEFwe334IdzNGgbDK3b93JOIpmzT3WXN8zHe1mH4T1OQyGpHOFXBxyKioJe8GZrkKdckZVt2ioGE2Gd0JSATTeyInZ512XqeRbbnA6fSESDFVZbHs6fhl7QIQrV+IYIHrZdbeubaUxmHCZZ/xIdA0zBYOf0Q8NDNWGlZhj3/wzjPc80ZdN8Idrq9Q8xYbnX1b43Mmmi1RdpeRGG1jaWxeLUZAi2dQTT3hxy7HQqkdhrZkM+SKHludlJcxNFOMuHfz762gPGV+3ycppyxM8NJQ/7PLE=
    - secure: He1u0jAsfS8mlSK76sBvDLB5xwQ0/augNP+mH3liI3Gcr+FvlM4gilSQItTflMJFD4JG9WKV7npuBL00kTLytHWgNpJpiSnBfIsgHGLl/EzUIdlobK63a0CM9xSdrkGZC6u+fSk+iYe1tBQrti9ICNnE0M4FcwxqnTyFr1vjxLVfuEsCissJa2+zB4woGrqijVAksOzXJfYoYWz2OytAL4IEsbSBYEwHgDLHAAYP/oix2bfKXM10LU1dgd13zFMpgGn4E2NMhYeqP4uGgY5DgTPDZ1zsxuMNd4UBD6auZYsVKyJX5cgoc7GybO8njWfo0CfgqkGAWmNFrnH5yJDHshkNDVtpPaYrXEx74ocNHFWJ2GVBD/CcYG8t6PhlTWuwuJhyySuGK1Jb77t6IKS4OKrmvseu40C3rXhzui0cLIwhmEtZORjNryioSuyeNUKpw2dxC+CJFxkGyQ9V82u9J3h7kEQ2GYDnyAVVPEG+sIkzMiFF7L0Vz8NmQskRh42xGFJwHb0jOcSiOwiAzWiTgkJRNFZbqZliW90IyKlfVZm2Xzmpl4HqaZLFuofXSudehSqRLk3aih0ETJigWi9Yqx2Dd0B9rpLHBuho3SpETOdUDM/aZztvzkAE5bFf4zA38+CJHwm0CotdIO7MnPC0S3VDPiDK7i4qLv4r9SyxbLo=